# Generated by Django 6.0.1 on 2026-01-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio_pics/')),
                ('github_link', models.URLField()),
                ('live_demo_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
