# Generated by Django 6.0.1 on 2026-01-17 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoilo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myproject',
            name='github_link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='image',
            field=models.ImageField(upload_to='portfolio_image/'),
        ),
    ]
