# Generated by Django 6.0.1 on 2026-05-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoilo', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='category',
            field=models.CharField(choices=[('demo', 'Demo Project'), ('client', 'Client Project')], default='demo', max_length=20),
        ),
    ]
